### ISSUE TITLE
Cannot build on IOS

### ISSUE THREAD

**Issue by Almya** [appfeel/analytics-google#21] opened 2019-01-28 14:57 UTC
When trying to build my app via XCode, I get an error in file `/src/ios/CDVGoogleAnalytics.m` : `Use of undeclared identifier 'FIRApp'`

![Screenshot](https://i.ibb.co/72sP6Mk/Screenshot-2019-01-28-at-15-49-43.png)

Xcode version: `10.1`
Cordova version: `8.1.2`
Ios platform version: `4.5.5`

**Comment by miqmago** [comment] 2019-01-28 15:32
Possible duplicate of https://github.com/appfeel/analytics-google/issues/19
Could you check if that applies? Reopen otherwise

**Closed as completed by miqmago** 2019-01-28 15:32 UTC

**Comment by Almya** [comment] 2019-01-28 23:14
Unfortunately it doesn't. I tried to add `Firebase` instead of `FirebaseAnalytics`, `Firebase` with `FirebaseAnalytics` but nothing change.

**Comment by SimonBrazell** [comment] 2019-01-31 04:31
I can see this issue is closed, what is the fix for this? 

I'm having the same problem with iOS builds using Cordova Ionic:

```
$ ionic info
Ionic:

   ionic (Ionic CLI)  : 4.10.1 (.nvm/versions/node/v8.14.0/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 3.1.1, (and 16 other plugins)

System:

   Android SDK Tools : 26.1.1 (Library/Android/sdk/)
   ios-deploy        : 1.9.4
   NodeJS            : v8.14.0 (.nvm/versions/node/v8.14.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

$ ionic cordova plugin ls
> cordova plugin ls
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-annotated-plugin-android 1.0.4 "cordova-annotated-plugin-android"
cordova-play-services-version-adapter 1.0.2 "Cordova/Ionic Google Play Services Versions Incompatibility Adapter"
cordova-plugin-analytics 2.0.0 "Google Analytics Firebase Plugin"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
onesignal-cordova-plugin 2.4.6 "OneSignal Push Notifications"
```

![screen shot 2019-01-31 at 3 19 23 pm](https://user-images.githubusercontent.com/16571951/52030370-9e5af400-256b-11e9-96c0-e001d8fb9be9.png)

I'm new to this plugin so it could be something I am missing so apologies is there is an obvious fix for this.

**Comment by supperdsj** [comment] 2019-04-06 19:55
same question here

**Comment by BinaryBlock** [comment] 2019-05-21 17:28
same question here

**Comment by fdambrosio** [comment] 2019-09-07 17:20
I have the same problem

**Comment by hyperlinked** [comment] 2019-09-11 17:24
I had the same issue. 

My environment info:
   Ionic Framework               : @ionic/angular 4.7.1
   @capacitor/core : 1.1.1
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Xcode      : Xcode 10.3 Build version 10G8

I was able to fix the issue by adding an import statement to import @FirebaseCore. The import statements at the top then look like this:

#import "CDVGoogleAnalytics.h"
**@import FirebaseCore;**
@import FirebaseAnalytics;

After that I ended up with a another issue with the debugger stopping execution of the app on startup. If you get that too, then look at this StackOverflow thread. If your issue was the same as mine, you have to add your Google-Info.plist file a specific way. Dragging it into the right directory might not work. 

https://stackoverflow.com/questions/45317777/could-not-find-a-valid-googleservice-info-plist-in-your-project

**Comment by miqmago** [comment] 2019-09-13 07:35
Thanks @hyperlinked 
Have you tried to add google-info.plist as cordova resource file?

See https://stackoverflow.com/a/45800644/513570:

```xml
<platform name="ios">
    <resource-file src="GoogleService-Info.plist" />
</platform>
```

**Comment by mikeCalvir** [comment] 2020-06-11 12:33
None of the Google docs mention FirebaseCore being needed for FIRApp, very frustrating!
Thanks @hyperlinked !
